### ISSUE TITLE
Policy Question: Should the AIP transition to Archivematica be lossless

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Digital-Preservation#10]
We have a number of different types of files which are in a Canadiana AIP:

* Source files  (images and born digital PDFs)
* Historical metadata records #4 #6 
* changelog.txt file which would be transformed into PREMIS
* bagit information for overall AIP, SIP and SIP revisions
* OCR data that is part of the access platform #5 

Should the goal be to preserve Canadiana's existing structure within Archivematica, or should we be transforming as if we had been using Archivematica all along (preserve all source files, bring in appropriate DC metadata, transform changelog.txt to indicate history of source files)

Should we separately from these primary AIPs be creating a set of 'historical structure' AIPs which store some of these files?

**Comment by enouserid** [comment]
I don't see any reason to worry about preserving the existing AIP structure; I'm not aware of any functional reason to do so. Before doing the conversion, we will need to advise/consult with our stakeholders to outline what we are doing and what structural information might be lost as a result, and see if there are any concerns, but I don't think that there is anything in the current SIP or AIP structure per se that would be considered important information to preserve by any significant stakeholder.

**Comment by RussellMcOrmond** [comment]
This question has been answered, so closing.  Anyone who has additional feedback can open a new issue.
