### ISSUE TITLE
Install latest Archivematica on test server (Internal LAN access only).

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Digital-Preservation#14]
This will be a first install by @hstgelais-crkn-rcdr , using a test server.

https://www.archivematica.org/en/docs/archivematica-1.12/

**Comment by hstgelais-crkn-rcdr** [comment]
Don't we want to install their 1.13.0 RC1 too? or just start with the current one for testing?

**Comment by RussellMcOrmond** [comment]
Yes (Meaning, do the install at least once using the exact instructions for the release version, and then also check out the RC1).

I expect that you'll want to install, wipe, install a few times.


I also want to test out indexing AIPs that were there from a previous install of Archivematica (IE: We should be able to point to a Swift container with AIPs in it, and then index them so they show up in Archivematica's console).

**Comment by hstgelais-crkn-rcdr** [comment]
The archivematica installation was done on oma located in Ottawa. You can reach it by going to 

http://10.200.1.30 (for now).

**Comment by hstgelais-crkn-rcdr** [comment]
The ip was reserved in the dc2.crkn.local DHCP and archivematica-test was added to hover under c7a.ca 

http://archivematica-test.c7a.ca/administration/accounts/login/

**Comment by hstgelais-crkn-rcdr** [comment]
To provision storage for the archivematica-test instance, I formatted the disks in the oma server and created a zpool to make it easy because swift is still not installed / configured. 

Zpool name is /archivematica-1 and created the directory structure from Archivematica.  I modified the storage location in the storage service to point to the new zpool directories.

**Comment by hstgelais-crkn-rcdr** [comment]
An archivematica sandbox instance is accessible at http://archivematica-test.c7a.ca when connected to the Wellington Fortinet VPN. A test user with admin privileges (arch-test / archivematica) was created to allow access to the instance.
