### ISSUE TITLE
CIFS to directory on \\crkn-nas\wip share on NAS server as transfer source

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Digital-Preservation#23]
The production staff currently use the NAS server as the destination for all scanned images.   Currently they use sftp to transfer to a storage space on Jarlsberg.  It would likely be much easier for them if a directory on the NAS server could be set up as the transfer source for Archivematica.

A CIFS connection should be made that is then treated as a regular directory for Archivematica.

It is likely best if the CIFS connection is made within the host OS, and then shared with the VM.  That way the same CIFS mount can potentially be used by multiple services (Docker images as well as VirtualBox)

**Comment by RussellMcOrmond** [comment]
NFS isn't already set up on the NAS server, but I believe the password for some generic logins are known for connecting using CIFS.  


```
[09:34] root@eclipse ~# smbclient -N -L crkn-nas
WARNING: The "syslog" option is deprecated

	Sharename       Type      Comment
	---------       ----      -------
	WIP             Disk      
	Backups         Disk      
	home            Disk      Home
	IPC$            IPC       IPC Service ()
Reconnecting with SMB1 for workgroup listing.

	Server               Comment
	---------            -------

	Workgroup            Master
	---------            -------
	CRKN                 
[09:35] root@eclipse ~# showmount -e crkn-nas.crkn.local
clnt_create: RPC: Port mapper failure - Unable to receive: errno 111 (Connection refused)
[09:35] root@eclipse ~# 
```

**Comment by hstgelais-crkn-rcdr** [comment]
The documentation of the qnap nas says that it runs QTS which is a Linux-based OS. It is NFS enabled but I can't get my hand on the Qnap admin password so I asked William how we should contact Gridway to get the password (and other passwords related to the CRKN.local domain).

Found documentation on how to mount a NFS share on Ubuntu => [link](https://sites.google.com/site/installationubuntu/qnap/qnap-nfs-shares-on-ubuntu)

**Comment by hstgelais-crkn-rcdr** [comment]
The current volume on the qnap is set to **Users, groups and computer permission** and not on NFS so unless we create a new volume to set it up as nfs, this is impossible to connect with NFS. CIFS is working thought. Check issue https://github.com/crkn-rcdr/Systems-Administration/issues/304

**Comment by RussellMcOrmond** [comment]
Fixed title :-)

**Comment by hstgelais-crkn-rcdr** [comment]
How is it realted to https://github.com/crkn-rcdr/Systems-Administration/issues/304?

**Comment by RussellMcOrmond** [comment]
Relationship to Sysadmin ticket discussed elsewhere, but for record.

This ticket is specific to Archivematica and its VM environment, and having a new transfer source set up for staff. Currently I believe they only have the sample transfers that come with Archivematica.

The other ticket is related to having a mount on the host itself, to be used by Docker containers.

This is also related to #16 , which is about setting the output for AIP  storage can be on Swift, rather than the local filesystem.

**Comment by hstgelais-crkn-rcdr** [comment]
The CIFS mount was configured in puppet under the archivematica.pp manifest. It was configured to use the **tdr** user and group. 

The mount was done at `/media/crkn-nas-wip`
