### ISSUE TITLE
Proposal: Store metadata updates within AIP that was updated

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Digital-Preservation#4]
Documentation for [AIP](https://github.com/crkn-rcdr/Digital-Preservation/blob/master/xml/published/schema/2012/txt/aip.txt) which can contain multiple [SIP](https://github.com/crkn-rcdr/Digital-Preservation/blob/master/xml/published/schema/2012/txt/sip.txt)s.

The AIP format allows a ".partial" revision, which would contain only a metadata.xml file and a manifest-md5.txt that was correct for the complete SIP that was updated.

Archivematica supports [Re-ingest](https://www.archivematica.org/en/docs/archivematica-1.9/user-manual/ingest/ingest/#reingest), which includes metadata only updates for descriptive metadata.  The proposal is to investigate what history Archivematica keeps for the previous descriptive metadata.

It might also be appropriate to store the previous METS record as a data file, in case someone had any reason to want to refer to them.

**Comment by nataliemacdonald** [comment]
I've been trying to find best practices for this question, but I haven't been lucky. I will continue to look, though. From what I've been able to read, Some cataloguing software and ILS track changes for operational, not archival, purposes. For example, UserX makes a change to the metadata that describes a group of 100 records. But, then UserX realizes that they made a mistake and wants to change it back. Some software offers an undo function, while others version the record, allowing it to be reverted to whatever version is needed. 

Personally, I believe that there is not a need to preserve descriptive metadata records. They are not static as standards and best practices are always changing. But, it would be nice to have versions, in case we do make a mistake. However, there may be multiple ways to solve that request.

**Comment by RussellMcOrmond** [comment]
I believe @nataliemacdonald described a user story ("UserX makes a change to the metadata that describes a group of 100 records") which I agree would apply to the access platform, but not to the preservation platform.  This specific project is trying to narrowly discuss features related to the digital preservation platform.

We should probably open a more general project in GitHub to discuss Access Platform features that would feed into the project planning process.  There are software project specific spaces, but not the Access Platform as a whole.   I think the library-like management of the Canadiana access platform will fairly regularly have descriptive metadata and other types of updates, and creating a future "undo" functionality for that environment would be very helpful for staff.

**Comment by nataliemacdonald** [comment]
Yes, you are right, Russell. I was definitely thinking about the Access platform. I took a look at the Archivematica documentation and it looks like the a reingest of metadata only will keep the original metadata in the dmdsec and add a new updated dmdsec. 

"This method is for adding or updating descriptive and/or rights metadata. Doing so will update the dmdSec of the AIP’s METS file. Note that the original metadata will still be present but if you scroll down you’ll also see another dmdSec that says STATUS=”updated”, like so"

**Comment by RussellMcOrmond** [comment]
It was decided, and confirmed by PAC, that we would only retain the most recent SIP and metadata with replacement Archivematica AIPs.
